name: Get Default Username and Email

on:
  push:
    branches:
      - main

jobs:
  get-username-email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display Default Username
      run: git config user.name

    - name: Display Default Email
      run: git config user.email
